version: '3.8'
services:
  web:
    container_name: nginx_${APP_NAME}_${ENVIROMENT}
    build:
      context: ./
      dockerfile: ./config/nginx/Dockerfile-nginx
      args:
        - home_domain=localhost
    links:
      - app
    ports:
      - 80:80
      - 443:443
    volumes:
      - ../public:/var/www/public
      - ./config/nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ../storage/logs/nginx:/var/log/nginx
    depends_on:
      - app
    networks:
      - local_network
networks:
  local_network:
    name: local_network
